spring.application.name=backend
spring.mongodb.uri = mongodb+srv://vallelili_user:Vallelili2026@cluster0.vo933qd.mongodb.net/
spring.mongodb.database = Vallelili_Capacitaciones


# Clave secreta para JWT — 
jwt.secret=valledeLiliCapacitacionSecretKey2024SuperSegura

# Tiempo de expiración en milisegundos (86400000 = 24 horas)
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
# Desactiva el usuario automático de Spring Security
# Esto no afecta  login JWT — solo evita que Spring genere su propio usuario
spring.security.user.name=disabled
spring.security.user.password=disabled